### ISSUE TITLE
Implement standard FormBuilder helpers

### ISSUE THREAD

**Issue by Spone** [pantographe/view_component-form#4]
## Helper methods

- [x] button #18
- [x] check_box
- [x] collection_check_boxes #29
- [x] collection_radio_buttons #29
- [x] collection_select
- [x] color_field
- [x] date_field
- [x] date_select #24
- [x] datetime_field
- [x] datetime_local_field
- [x] datetime_select #24
- [x] email_field
- [x] ~~fields~~
- [x] ~~fields_for~~
- [x] file_field #28 
- [x] grouped_collection_select #23
- [x] ~~hidden_field~~
- [x] label
- [x] month_field
- [x] number_field
- [x] password_field
- [x] phone_field
- [x] radio_button #15
- [x] range_field
- [x] rich_text_area #30
- [x] search_field
- [x] select
- [x] submit
- [x] telephone_field
- [x] text_area
- [x] text_field
- [x] time_field
- [x] time_select #24
- [x] time_zone_select #24
- [x] url_field
- [x] week_field

## ViewComponents

- [x] Form::ButtonComponent #18
- [x] Form::CheckBoxComponent #14
- [x] Form::CollectionCheckBoxesComponent #29
- [x] Form::CollectionRadioButtonsComponent #29
- [x] Form::CollectionSelectComponent #23
- [x] Form::ColorFieldComponent
- [x] Form::DateFieldComponent
- [x] Form::DateSelectComponent #24
- [x] Form::DatetimeFieldComponent
- [x] Form::DatetimeLocalFieldComponent
- [x] Form::DatetimeSelectComponent #24
- [x] Form::EmailFieldComponent
- [x] ~~Form::FieldsComponent~~
- [x] ~~Form::FieldsForComponent~~
- [x] Form::FileFieldComponent #28
- [x] Form::GroupedCollectionSelectComponent #23
- [x] ~~Form::HiddenFieldComponent~~
- [x] Form::LabelComponent
- [x] Form::MonthFieldComponent
- [x] Form::NumberFieldComponent
- [x] Form::PasswordFieldComponent
- [x] Form::RadioButtonComponent #15
- [x] Form::RangeFieldComponent
- [x] Form::RichTextAreaComponent #30
- [x] Form::SearchFieldComponent
- [x] Form::SelectComponent #20
- [x] Form::SubmitComponent #17
- [x] Form::TelephoneFieldComponent
- [x] Form::TextAreaComponent #19
- [x] Form::TextFieldComponent
- [x] Form::TimeFieldComponent
- [x] Form::TimeSelectComponent #24
- [x] Form::TimeZoneSelectComponent #24
- [x] Form::UrlFieldComponent
- [x] Form::WeekFieldComponent

**Comment by Spone** [comment]
:rocket: :rocket: :rocket:
